Add necessary comments to the code #39
hetulbhatt/KeyFlow pull request #44
Opened 2023-09-03 18:52 UTC by chavi362

2023-09-08 18:13 UTC, hetulbhatt requested changes
Great job, @chavi362! Your comments look good overall. However, I have a few PR-level comments for you:

1. **Consistent Capitalization in Comments**
   - Please make sure that the capitalization in your comments is consistent throughout the codebase. For example:
     - Good: `// Initialize the variable.`
     - Bad: `// initialize the variable.`

2. **Spacing After "//" in Comments**
   - When writing comments, make sure to leave a space after the "//" characters. For instance:
     - Good: `// This is a comment.`
     - Bad: `//This is a comment.`

3. **Spacing Before Comments on the Same Line as Code**
   - If you place a comment on the same line as the code, make sure to leave a space before starting the comment. For example:
     - Good:
       ```cpp
       int x = 5;  // Initialize x.
       ```
     - Bad:
       ```cpp
       int x = 5;//Initialize x.
       ```

4. **End Comments with a Full Stop**
   - Please remember to end your comments with a full stop. It helps in making comments more complete and clear. For instance:
     - Good: `// This is a comment.`
     - Bad: `// This is a comment`

Please address these points in your code. Thanks!

2023-09-08 18:13 UTC, hetulbhatt commented on KeyFlow/helper.hpp
> +	//removes the removes leading and trailing spaces from str
remove the extra "remove"

2023-09-08 18:13 UTC, hetulbhatt commented on KeyFlow/helper.hpp
> +	//nitializes the key_to_vkcode unordered map using an initializer list.
Correct typo: "nitializes"

2023-09-08 18:13 UTC, hetulbhatt commented on KeyFlow/helper.hpp
> +	//Each key-value pair corresponds to a key (represented as a std::string) and a value (represented as an int) according to the table in the Readmy
Correct typo: "Readmy"

2023-09-08 18:13 UTC, hetulbhatt commented on KeyFlow/keyhook.hpp
> +	//provides the only way to access the single instance of the KeyHook class. It returns a reference to the hook member variable of the KeyHookSingleton instanc
Correct typo: "instanc"

2023-09-08 18:13 UTC, hetulbhatt commented on KeyFlow/keystroke_handler.hpp
> +	//nstructor that initializes the sequence variable to 0 and sets all elements of the logs array to 0 using memset.
Correct typo: "nstructor"

2023-09-08 18:13 UTC, hetulbhatt commented on KeyFlow/keystroke_handler.hpp
> +	//akes an integer size as a parameter and resizes the buffer vector accordingly.
Correct typo: "akes"

2023-09-08 18:13 UTC, hetulbhatt commented on KeyFlow/keystroke_handler.hpp
> +	//- It takes a DWORD parameter vk_code representing the virtual key code of the pressed key and an int parameter isDown indicating whether the key is pressed or released.
Remove the hyphen before " It takes..."

2023-09-08 18:13 UTC, hetulbhatt commented on KeyFlow/logger.hpp
> +	static std::ofstream logFile;//his member variable will be used to write log messages to a file
Correct typo: "his"

2023-09-08 18:13 UTC, hetulbhatt commented on KeyFlow/logger.hpp
> +	//his static member function is used to initialize the logger. It creates a directory named "logs" (if it doesn't already exist) using the _mkdir() function from <direct.h>.
Correct typo: "his"

2023-09-08 18:13 UTC, hetulbhatt commented on KeyFlow/KeyFlow.cpp
> +	///initialize the logger. It creates a directory named "logs" (if it doesn't already exist) then opens the file for writing
Remove an extra "/" from the comment

2023-09-10 17:40 UTC, hetulbhatt commented
@chavi362, just let me know once you resolve all the issues, and don't forget point 3. Thanks.

"3. Spacing Before Comments on the Same Line as Code"

2023-09-10 17:42 UTC, chavi362 commented
Fixed! Yes I did it! thank you for the review, I've learned a lot

‫בתאריך יום א׳, 10 בספט׳ 2023 ב-20:40 מאת ‪Hetul Bhatt‬‏ <‪
***@***.***‬‏>:‬

> @chavi362 <https://github.com/chavi362>, just let me know once you
> resolve all the issues, and don't forget point 3. Thanks.
>
> "3. Spacing Before Comments on the Same Line as Code"
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hetulbhatt/KeyFlow/pull/44#issuecomment-1712893878>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BBPQEONK3PZJWYDFJDFGRO3XZX3Q3ANCNFSM6AAAAAA4JPUMSU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-09-10 17:48 UTC, hetulbhatt commented
@chavi362, merging this PR then. Thanks for the efforts. Please close the issue assigned to you. You can start looking into some other issue too, if you want to, as you're now well acquainted with the code base.

2023-09-10 17:50 UTC, merged

2023-09-10 18:00 UTC, chavi362 commented
Thanks!!
I would like to work on another issue,
but now I see that all the issues currently assigned to others.
Is there any issue I could work on?

‫בתאריך יום א׳, 10 בספט׳ 2023 ב-20:51 מאת ‪Hetul Bhatt‬‏ <‪
***@***.***‬‏>:‬

> Merged #44 <https://github.com/hetulbhatt/KeyFlow/pull/44> into develop.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hetulbhatt/KeyFlow/pull/44#event-10326994603>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BBPQEOIVHKUG6OW5KCBBHKDXZX4YJANCNFSM6AAAAAA4JPUMSU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-09-10 18:25 UTC, hetulbhatt commented
Just created a new issue. It's a bug this time. Please have a look: https://github.com/hetulbhatt/KeyFlow/issues/45